version: '3.8'

services:
  bot:
    build: .
    user: "1000:1000"
    env_file: .env
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    ports:
      - "5678:5678"
    restart: unless-stopped