name: Build and Deploy Docker Container

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
    - name: Clean up problematic files
      run: |
        sudo find /home/gabi/github/Discord_Advanced_LoL_Stats/actions-runner/_work -name "__pycache__" -exec sudo rm -rf {} + 2>/dev/null || true
        sudo find /home/gabi/github/Discord_Advanced_LoL_Stats/actions-runner/_work -name "*.pyc" -exec sudo rm -f {} + 2>/dev/null || true

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Copy environment file
      run: |
        cp /home/gabi/github/Discord_Advanced_LoL_Stats/.env ./

    - name: Stop existing containers
      run: |
        cd /home/gabi/github/Discord_Advanced_LoL_Stats
        docker-compose down || echo "No containers to stop"

    - name: Pull latest changes and rebuild
      run: |
        cd /home/gabi/github/Discord_Advanced_LoL_Stats
        git pull origin main
        docker-compose build --no-cache
        docker-compose up -d

    - name: Clean up unused Docker images
      run: |
        docker image prune -f

    - name: Fix file permissions
      run: |
        sudo chown -R gabi:gabi ${{ github.workspace }} || true 