name: Build and Deploy Docker Container

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
    - name: Clean up problematic files
      run: |
        sudo find /home/gabi/github/Discord_Advanced_LoL_Stats/actions-runner/_work -name "__pycache__" -exec sudo rm -rf {} + 2>/dev/null || true
        sudo find /home/gabi/github/Discord_Advanced_LoL_Stats/actions-runner/_work -name "*.pyc" -exec sudo rm -f {} + 2>/dev/null || true

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Copy environment file
      run: |
        cp /home/gabi/github/Discord_Advanced_LoL_Stats/.env ./

    - name: Copy database file
      run: |
        # Copy the database file from the persistent location
        if [ -f /home/gabi/github/Discord_Advanced_LoL_Stats/src/database/lol_database.db ]; then
          echo "Copying database from persistent location..."
          cp /home/gabi/github/Discord_Advanced_LoL_Stats/src/database/lol_database.db ./src/database/
          echo "Database copied successfully"
        else
          echo "WARNING: Database file not found in persistent location!"
        fi

    - name: Ensure database permissions and initialization
      run: |
        # Debug information
        echo "Current working directory: $(pwd)"
        echo "Database file status:"
        ls -la ./src/database/ || echo "src/database directory does not exist"
        ls -la ./data/ || echo "data directory does not exist"
        
        # Ensure the database directory and files have correct permissions
        sudo mkdir -p ./data
        sudo chown -R 1000:1000 ./data || true
        sudo chown -R 1000:1000 ./src/database || true
        sudo chmod -R 755 ./src/database || true
        
        # Ensure database file is readable and has tables
        if [ -f ./src/database/lol_database.db ]; then
          echo "Database file exists, checking tables:"
          sqlite3 ./src/database/lol_database.db ".tables" || echo "Failed to read database tables"
          echo "Database file size: $(stat -c%s ./src/database/lol_database.db) bytes"
        else
          echo "Database file does not exist!"
        fi
        
        # Show final permissions
        echo "Final permissions:"
        ls -la ./src/database/ || echo "src/database directory issue"
        ls -la ./data/ || echo "data directory issue"

    - name: Stop existing containers
      run: |
        docker-compose down || echo "No containers to stop"

    - name: Pull latest changes and rebuild
      run: |
        git pull origin main
        docker-compose build --no-cache
        docker-compose up -d

    - name: Clean up unused Docker images
      run: |
        docker image prune -f

    - name: Fix file permissions
      run: |
        sudo chown -R gabi:gabi ${{ github.workspace }} || true 